### ISSUE TITLE
CTRG_TRP Uniform Space

### ISSUE THREAD

**Issue by dancemoox** [kami-/hull3#128]
CTRG Tropical uniforms lack sufficient space for both radios and regular gear assignments. Not checked the other CTRG sub types.

**Comment by Cyruz143** [comment]
Needs to go in https://github.com/Satire-/ARK_Replacer

**Comment by Cyruz143** [comment]
https://github.com/Cyruz143/ark_replacer/commit/c9a21ed46f1196632fc613cd8d2e58083573caaa

Can close
