### ISSUE TITLE
CUP_TKA_OD Uniform space issues

### ISSUE THREAD

**Issue by Draakon0** [kami-/hull3#147]
The CO, Medic and XO vest's don't have enough space for the CUP_TKA_OD faction gear (FAL_TKA). Tested with a fresh mission from Shipyard. 

> 
> 22:54:15 "0         [WARN]    hull3.gear.assign                Failed to assign 1x'hlc_20Rnd_762x51_T_fal' (of 2) from 'vestMagazines' to the vest of unit 'O Alpha 1-1:1' from template 'FAL_TKA' and class 'CO'."
> 22:54:15 "0         [WARN]    hull3.gear.assign                Failed to assign 2x'SmokeShell' (of 4) from 'vestMagazines' to the vest of unit 'O Alpha 1-1:2 (Draakon)' from template 'FAL_TKA' and class 'Medic'."
> 22:54:15 "0         [WARN]    hull3.gear.assign                Failed to assign 1x'hlc_20Rnd_762x51_T_fal' (of 2) from 'vestMagazines' to the vest of unit 'O Alpha 1-1:4' from template 'FAL_TKA' and class 'XO'."
> 22:54:15 "0         [WARN]    hull3.gear.assign                Failed to assign 2x'SmokeShell' (of 4) from 'vestMagazines' to the vest of unit 'O Alpha 1-2:2' from template 'FAL_TKA' and class 'Medic'."

**Comment by dancemoox** [comment]
Fixed with #148
