### ISSUE TITLE
Request to define uniform items

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#23]
As per below, a way we can store stuff in the uniform, this will make assigning medical gear much nicer for A3 as you won't have to include bandages in magazines[] meaning less chance of people breaking medical gear assigns, proposed solution below.

        uniformMagazines[] = {
            {"bandages", 5}
        };
        magazines[] = {
            {"hlc_30Rnd_545x39_B_AK", 8},
            {"SmokeShell", 2},
            {"HandGrenade", 2}
        };
        vestMagazines[] = {
            {"hlc_30Rnd_545x39_B_AK", 8}
        };

This in theory means when you define uniformMagazines on the base classes, when you come to the AR you don't need to redefine the medical gear every time.

Thoughts?

**Comment by kami-** [comment]
Why not call it `medicalGear` if you just want to use it for medical gear only? Also since we are going to break backwards compatibility for AGM, we can add more specialized fields, like `radios` and stuff.

**Comment by Cyruz143** [comment]
Agreed, if you're happy to do that before we set off on the huge task for making 46 sets of gear templates.

**Comment by kami-** [comment]
Added in v0.4.0.
