### ISSUE TITLE
Wrong classname for CAS vehicleClassnames on select faction templates.

### ISSUE THREAD

**Issue by Draakon0** [kami-/hull3#233]
The following factions have "CUP_B_A10_AT_DYN_USA" as their CAS vehicleClassnames:

USM_USA_80_WD
USM_USMC_80_WD
USM_USA_90_WD
USM_USMC_90_WD
USM_RAN_90_WD
USM_USA_70_OD
MNP_US_WD

That classname does not exist anymore (it is just "CUP_B_A10_DYN_USA" now, like on the MNP_US_RAN template).

**Comment by Cyruz143** [comment]
https://github.com/kami-/hull3/pull/234
