### ISSUE TITLE
Review weather/time sync

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#25]
Especially for JIP.

Still seem to be having issues with this but we'll need to do some proper testing. Fog still seems inconsistent and hosts changing the weather doesn't seem to propagate correctly.

Possibly ```ForceWeatherChange``` isn't working as expect as I have to run it multiple times for it to sync to everyone.

**Comment by kami-** [comment]
Removed weather synchronization. In BIS and ACE we trust.
