### ISSUE TITLE
Hiding seagulls

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#27]
Not sure if this should be in Hull or spec itself but makes sense for the respawn handler I guess.

Current:
```
hull3_unit_fnc_onPlayerRespawn = {
    DEBUG("hull3.player.respawned",FMT_1("Player has respawned with '%1'",_this));
    ["player.respawned", _this] call hull3_event_fnc_emitEvent;
};
```

Proposed: 
```
hull3_unit_fnc_onPlayerRespawn = {
    DEBUG("hull3.player.respawned",FMT_1("Player has respawned with '%1'",_this));
    ["player.respawned", _this] call hull3_event_fnc_emitEvent;
    {if(_x isKindOf "seagull")then{_x setPos [0,0,100]};
    }forEach nearestObjects [player, [], 250];
};
```

Code is a massive hatchet job, untested and probably wrong. Hopefully good enough for illustration purposes though!

**Comment by sojunator** [comment]
Why not just change the config for seagulls? Remove their shound and change models to something invis or a butterfly.

**Comment by Cyruz143** [comment]
Remove their what? Shound? Calm down Gold Member...

All joking aside change the models to butterflys would be better, thats what ACE did with A2. Anyone fancy writing a config patch or proposing it to AGM and submitting it?

**Comment by Cyruz143** [comment]
ACE_spec does this and I've muted the seagulls via config, considering closed.
