### ISSUE TITLE
RPG ammo use review

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#280]
CUP has these rockets available:

- `CUP_PG7V_M` - Light AT
- `CUP_PG7VM_M` - Light AT
- `CUP_PG7VL_M` - Medium AT
- `CUP_PG7VR_M` - Medium AT
- `CUP_TBG7V_M` - Thermobaric
- `CUP_OG7_M` - Frag

The iron sights have two stages, the first stage supports `CUP_PG7V_M` and `CUP_PG7VM_M`. The second stage covers `CUP_PG7VL_M` and `CUP_OG7_M`. Anything else requires the MAT scope!

I'd suggest we switch the default loadout for RAT RPGs to use `CUP_PG7VM_M` it has slightly more armour penetration and still works on the default ranging (avoids confusion for players).

MAT, might be worth not mixing `CUP_PG7VL_M` and `CUP_PG7VR_M` together, maybe just give them the more powerful round so they're consistent on the scope use!

**Comment by dancemoox** [comment]
You can close this now I've done #343
