### ISSUE TITLE
SetDate broken

### ISSUE THREAD

**Issue by dancemoox** [kami-/hull3#33]
Set defaults in description.ext are ignored when you kick a mission. Causes what should be clear and full moon night to be clear and no moon. Meaning its so dark you can walk off the side of a carrier without knowing it.

**Comment by Cyruz143** [comment]
Tested on dedi:

Client results:
New Moon: ```2035,1,24,4,50```
Full Moon ```2035,1,31,4,50```

**Comment by Cyruz143** [comment]
Server results:
New Moon: ```2014,1,24,4,50```
Full Moon: ```2014,1,31,4,50```

**Comment by Cyruz143** [comment]
Logged with BI
http://feedback.arma3.com/view.php?id=24600

**Comment by Cyruz143** [comment]
OK so that's been a bug for ever. Let's fine some 2035 dates to use instead for now!

**Comment by dancemoox** [comment]
Ah well the bug will fix itself in 20 years, long before BI look at it..

**Comment by Cyruz143** [comment]
@dancemoox you happy to source two values from 2035 that work?

**Comment by dancemoox** [comment]
I've not tested these values in MP yet but fingers crossed they should be about right. It might not be technically correct the newest of new moons or the fullest of full moons but it is dark and bright.

Values:
New Moon 1st June 2035
Full Moon 12th June 2035

The night truly is dark and full of terrors..

**Comment by Cyruz143** [comment]
Fixed in https://github.com/kami-/hull3/pull/35
