### ISSUE TITLE
GER_DE + HK416 are incompatible.

### ISSUE THREAD

**Issue by purrcat259** [kami-/hull3#34]
RPT gets flooded with:

> 9:12:45 "0         [WARN]    hull3.gear.assign                Failed to assign 1x'HandGrenade' (of 1) from 'uniformMagazines' to the uniform of unit 'B Alpha 1-1:1 (Winter)' from template 'HK416' and class 'CO'."

Units get normal M4s I think instead, I imagine whatever the default is.

Full relevant RPT errors:
http://hastebin.com/ohuxopilex.md

**Comment by Cyruz143** [comment]
HK416 is placeholder atm due to lack of GL varients, would advise you don't use.

**Comment by Cyruz143** [comment]
Will fix when Toadie G36s are in repo
