### ISSUE TITLE
MNP_Vest_OD_A_ARM no longer exist

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#351]
MNP_Vest_OD_A_ARM
MNP_Vest_OD_B_ARM

Are nuked because old MNP and they're used.

**Comment by dancemoox** [comment]
MNP DPR Summer and Autumn need an overhaul as do the Soviet Airborne pyjama people.

**Comment by dancemoox** [comment]
Can close this now, vests were fixed in #352

**Comment by Cyruz143** [comment]
https://github.com/kami-/hull3/pull/352
