### ISSUE TITLE
Advanced ACRE2 features

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#36]
As per admin discussion, just jotting down a few points for later reference, label enhancement as required, this isn't a bug.

* 343's using squad names (Alpha/Bravo etc)
* Set ears for radios by default (http://acre.idi-systems.com/api/api_general.html#acre_api_fnc_setRadioSpatial)
* Automatic channel assignment based on squad e.g. Pilots on channel 2 on the 152 / Bravo members start on channel 2 etc (http://acre.idi-systems.com/api/api_general.html#acre_api_fnc_setCurrentRadioChannelNumber)

**Comment by kami-** [comment]
Preferred ear setup is different for users, not something you want to set.
Automatic channel assignment is not as easy as it sounds. It might need adding an extra config for the init line for each unit. IMHO it doesn't worth it, you should be able to switch channels on your own (especially if they have proper names).

**Comment by Cyruz143** [comment]
I thought about the automatic assignment, could be done using https://community.bistudio.com/wiki/roleDescription then fallback to default if not in expected list?

Setting ears is open to debate I guess, just saves time and I'm sure people would adjust if 343 is always left or right, one less thing to do, again, not mega important though, perhaps ask user base?

**Comment by Cyruz143** [comment]
```roleDescription``` is in stable now, can we have a look at this.

**Comment by Cyruz143** [comment]
Still want to take a look at this Kami, rather than ```roleDescription``` we could use ```groupId``` which is what we use for the ST markers to get the correct coloring, should work on the same principal.

**Comment by Cyruz143** [comment]
Closed with https://github.com/kami-/hull3/commit/f9cae5b96bd6a950bf9ccf875fbedeb6aa63f98b

Leaving the ears things as @kami- points out, it's too personal to set. The 343 naming requires overwriting a function in ACRE which we should avoid.
