### ISSUE TITLE
Removal of Chat box

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#61]
This is personal hatred of mine, we culled the channels in https://github.com/kami-/hull3/commit/d274ee6cc4fadbc76e0667f3edbf22e78942cec4 but we're still getting spam from Steam and disconnects and stuff.

Will PR something with: 
https://community.bistudio.com/wiki/showChat
https://community.bistudio.com/wiki/shownChat.

Possible issues, no-one will be able to use Chat in-game for technical issues, can't dead chat in ACE spec anyway so no need to worry about that. Admins need exclusion for mission commands and using global chat.

@kami- Have any objections to this?

**Comment by kami-** [comment]
For one, safety timer. Also makes debugging to chat impossible.

**Comment by Cyruz143** [comment]
Was going to write it as an event post safety timer, debugging is an actual problem...

**Comment by Cyruz143** [comment]
Yeah, this is more trouble than it's worth!
