### ISSUE TITLE
ACRE2 fix for update

### ISSUE THREAD

**Issue by Cyruz143** [kami-/hull3#69]
https://github.com/kami-/hull3/commit/c4c72a2a56910581d18a9f98c065fb31e0a5b264

That needs to go back to 0.7 when we move the latest ACRE2 (and move to A3...)

**Comment by kami-** [comment]
Is this still needed?

**Comment by Cyruz143** [comment]
Still needed, later patches change default volume and I'll forget!

**Comment by Cyruz143** [comment]
Fixed with https://github.com/kami-/hull3/commit/1551e55af380759a8120bd0cc654b36cfbe774b7
