### ISSUE TITLE
RPT Spam: Wrong color format #any

### ISSUE THREAD

**Issue by Draakon0** [kami-/hull3#83]
RPT is constantly getting spammed by this line: "Wrong color format #any". Happens in the new Eden 3D Editor.

Steps to reproduce:
1. Boot up A3 with ARK modset.
2. In main menu, go to editor and 3D editor.
3. Place down a playable unit and maybe some AI dudes belonging to playable unit group.
4. Hit Play Scenario.
5. Once able, return back to the edior.
6. Enjoy the RPT spam until you hit preview again or exit the editor.
7. Before you do that, pressing M to open up 2D editor, you can see the Hull3 Fireteam Markers (small yellow triangles) represented on the units you placed down before as well as their position being updated on the map if you move the units around in the editor.

**Comment by Draakon0** [comment]
http://webcache.googleusercontent.com/search?q=cache:gPGuNXI3WBsJ:feedback.arma3.com/print_bug_page.php%3Fbug_id%3D25948+&cd=3&hl=et&ct=clnk&gl=ee

During some google foo, I managed to dig up this from Google Cache (its from the A3 Feedback tracker)

**Comment by kami-** [comment]
This is not Hull related. Issue still persists with Hull removed from loaded addons.
